spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001

spring:
  profiles: dev
  application:
    name: microservicecloud-config-eureka-client

eureka:
  instance:
    hostname: eureka8001.com
  client:
    register-with-eureka: false #当前的eureka-server自己不需要注册进服务列表中
    fetch-registry: false #不通过eureka获取注册信息
    service-url:
      defaultZone: http://eureka8001.com:8001/eureka/
---
server:
  port: 8001

spring:
  profiles: test
  application:
    name: microservicecloud-config-eureka-client
eureka:
  instance:
    hostname: eureka8001.com
  client:
    service-url:
      defaultZone: http://eureka-dev.com:8001/erueka/

